### ISSUE TITLE
[error] backend port not found: :inotifywait

### ISSUE THREAD

**Issue by Slavenin** [koudelka/visualixir#13]
Hi!
When i run Visualixir
```bash
elixir --sname visualixir --hidden -S mix phoenix.server
```
 i see in console:
![](http://res.cloudinary.com/post-hawk/image/upload/v1479380523/ecd3dc316d04_001_sa3ggc.png)

**Comment by NobbZ** [comment]
This is not a problem with visualixir but phoenix in development mode. It
watches for filechanges and uses a couple of backends for this task, in
your case it choose `:intofywait` which is not available on your system.

Visualixir should run regardless of this message, only when you develop on
it yourself, it might take some time until changes of the files are
realized and acted upon.

To make it work in general you might install `*inotify-tools*` (Ubuntu
assumed).

Max <notifications@github.com> schrieb am Do., 17. Nov. 2016 um 12:04 Uhr:

**Comment by Slavenin** [comment]
Tnx!

**Comment by koudelka** [comment]
❤️@NobbZ
