### ISSUE TITLE
Process info

### ISSUE THREAD

**Issue by Slavenin** [koudelka/visualixir#15]
Hi!
It is not enough for viewing one process information like in observer.

**Comment by koudelka** [comment]
Hey there, I don't quite understand what you're asking, but maybe you can submit a PR?

**Comment by Slavenin** [comment]
Sorry for my english. I want see full process info (state, etc.) If i dbl click in observer application tree it open new window with detail information about selected process. In visualixir can do something like this?

**Comment by koudelka** [comment]
No problem. Visualixir doesn't do that at the moment. I'm holding off on adding new features until I can rewrite the frontend in Elm, sorry. If you've got any suggestions as to how it should look/behave, I'm all ears. :)

**Comment by Slavenin** [comment]
Why elm? о_О Why not React?

**Comment by koudelka** [comment]
I really don't like javascript. :)
