### ISSUE TITLE
CSS broken on mac?

### ISSUE THREAD

**Issue by luc-tielen** [koudelka/visualixir#17]
Hi, 

I want to showcase one of our applications at the company using this app to newcomers.. however, the GUI looks nothing like the gif in the README.

1. The drawing area is very limited in height, hard to see everything (I think normally it is almost full screen)
2. The icons nex to the 'exited', ... messages are too big (think half a screen).

I suspect these issues are related, maybe it only shows up properly on Linux?
Might this also be related to this being slightly outdated (old phoenix version, ...)?

Screenshot for clarity:
<img width="1680" alt="visualixir_css_bug" src="https://user-images.githubusercontent.com/3411018/39405188-fa03c912-4ba0-11e8-994e-95c253040bf4.png">

**Comment by luc-tielen** [comment]
Nvm, forgot to run brunch, it starts to look more like your gif... but now nothing is showing up and I get a page timeout.

**Comment by luc-tielen** [comment]
And nvm last issue, also.. restarting it fixed it!
Closing this issue.. sorry for "spam".

**Comment by koudelka** [comment]
no worries.

the project does need a bit of love, i just don't have a lot of time right now. :(

**Comment by luc-tielen** [comment]
Well, maybe make some issues for things you think need updating/fixing.. over a few weeks I have some spare time.
Mostly backend though, so if there is CSS-related stuff.. that might be harder.
Or is it mostly outdated phoenix / ... versions?

**Comment by koudelka** [comment]
all of the above. :)

i do backend work mostly, too, which probably explains the terrible UI.

**Comment by luc-tielen** [comment]
Well I gave a presentation about Elixir today with my colleague, using this tool. 
Was well received!
I'll try to do some PR's back, but can't promise when :)...
Thanks!

**Comment by koudelka** [comment]
Hey that's great to hear!

No pressure for the PRs, just if you feel inspired. :)
