### ISSUE TITLE
Followed readme, ran into problem

### ISSUE THREAD

**Issue by jonator** [koudelka/visualixir#25]
After following instructions on README, running `elixir --sname visualixir --hidden -S mix phoenix.server` gave me `** (Mix) The task "phoenix.server" could not be found`

Not being experienced with Elixir leaves me stumped! Thanks

**Comment by NobbZ** [comment]
`mix phx.server` should work. It seems as if the Readme hasn't been updated after the bump to phoenix 1.3…

**Comment by koudelka** [comment]
sorry about that dudes, i'll fix that up.

**Comment by jonator** [comment]
It may help to remind the user to `cd ..` out of the assets folder for ease of use.
