### ISSUE TITLE
tracing color on circles

### ISSUE THREAD

**Issue by amokan** [koudelka/visualixir#3]
I'm colorblind and cannot for the life of me tell the difference between a node in 'tracing' mode vs not. I had to dig through the code to figure it out because I thought I was losing my mind after looking at your gifs in action :)

Any chance you'd be interested in making the color difference more obvious? I can throw together a pull request, but you may not want me choosing colors.

Awesome tool, though!

**Comment by amokan** [comment]
@koudelka haha. well, i'll see if I can get someone to glance at this with me and give me some color feedback and I'll toss a PR your way when I get a chance.

Thanks!

**Comment by koudelka** [comment]
sounds good :)
